spring:
  profiles:
    active: peer1
  application:
    name: eureka-server-cluster
  security:
    user:
      name: eureka
      password: eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true